services:
  ticketomancy:
    build: .
    image: ticketomancy
    container_name: ticketsdev
    restart: always
    working_dir: /tickets
    command: ["yarn", "start", "--trace-warnings"]
    volumes:
      - ./:/tickets
      - ./config:/tickets/config
      - ./data/transcripts:/tickets/transcripts
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: ticketsdevdb
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017