services:
  ticketomancy:
    build: .
    image: ticketomancy
    container_name: tickets
    restart: always
    working_dir: /usr/src/app
    command: ["yarn", "start", "--trace-warnings"]
    volumes:
      - ./:/usr/src/app
      - ./data:/usr/src/app/data
      - ./data/transcripts:/usr/src/app/data/transcripts
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: ticketsdb
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017